### ISSUE TITLE
Katacoda is :skull: (switch to killercoda url)

### ISSUE THREAD

**Issue by adriens** [schemacrawler/SchemaCrawler-Katacoda-Scenarios#2]
Switch to Go to https://killercoda.com/schemacrawler for up-to-date Schemacrawler course
![image](https://user-images.githubusercontent.com/5235127/177643980-dcc49f5f-abd1-4b20-a4ae-79f8dc13ca0a.png)

**Comment by schemacrawler** [comment]
Thanks, @adriens - this is fixed now.

**Comment by adriens** [comment]
:zap:
